# Kafka Message Queue Configuration
spring:
  kafka:
    bootstrap-servers: 10.10.80.109:9092
    
    # Producer configuration
    producer:
      bootstrap-servers: 10.10.80.109:9092  # 明确指定生产者服务器
      acks: 1                    # 主节点写入成功后返回
      retries: 3                 # 失败重试次数
      batch-size: 16384          # 16KB批次大小
      buffer-memory: 33554432    # 32MB处理缓冲区
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        linger.ms: 100                     # 批次空闲时间
        request.timeout.ms: 5000           # 请求超时时间
        max.in.flight.requests.per.connection: 1  # 保证严格有序
        security.protocol: SASL_PLAINTEXT
        sasl.mechanism: SCRAM-SHA-256
        sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="test-7" password="test-7";
    
    # Consumer configuration
    consumer:
      bootstrap-servers: 10.10.80.109:9092  # 明确指定消费者服务器
      group-id: kline-service
      enable-auto-commit: false   # 禁用自动提交
      auto-offset-reset: earliest # 设置偏移量重置策略为从最早开始消费
      max-poll-records: 50        # 设置每次poll的最大消息条数
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        session.timeout.ms: 10000    # 会话超时时间
        request.timeout.ms: 5000     # 请求超时时间
        max.poll.interval.ms: 300000 # 最大poll间隔时间
        security.protocol: SASL_PLAINTEXT
        sasl.mechanism: SCRAM-SHA-256
        sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="test-7" password="test-7";
    
    # Listener configuration
    listener:
      type: single                   # 单条消费single, 批量消费为batch
      ack-mode: manual_immediate     # 设置ACK模式为手动立刻提交
      auto-startup: true        # 生产环境启用自动启动
      concurrency: 1           # 单线程消费保证有序性
      missing-topics-fatal: false

# Topic configurations
app:
  kafka:
    topics:
      timeline: timeline
    consumer:
      timeline:
        topic: timeline
        group: kline-service
        auto-startup: true
        concurrency: 1